/**
 * World Currency Registry - Complete 160+ ISO 4217 Currency Dictionary with Flags and Real Names
 */

export const worldCurrencies = {
  USD: { name: "US Dollar", symbol: "$", flag: "🇺🇸" },
  INR: { name: "Indian Rupee", symbol: "₹", flag: "🇮🇳" },
  EUR: { name: "Euro", symbol: "€", flag: "🇪🇺" },
  AED: { name: "UAE Dirham", symbol: "د.إ", flag: "🇦🇪" },
  GBP: { name: "British Pound", symbol: "£", flag: "🇬🇧" },
  SAR: { name: "Saudi Riyal", symbol: "﷼", flag: "🇸🇦" },
  QAR: { name: "Qatari Riyal", symbol: "QR", flag: "🇶🇦" },
  KWD: { name: "Kuwaiti Dinar", symbol: "KD", flag: "🇰🇼" },
  BHD: { name: "Bahraini Dinar", symbol: "BD", flag: "🇧🇭" },
  OMR: { name: "Omani Rial", symbol: "OMR", flag: "🇴🇲" },
  SGD: { name: "Singapore Dollar", symbol: "$", flag: "🇸🇬" },
  CAD: { name: "Canadian Dollar", symbol: "$", flag: "🇨🇦" },
  AUD: { name: "Australian Dollar", symbol: "$", flag: "🇦🇺" },
  CNY: { name: "Chinese Yuan", symbol: "¥", flag: "🇨🇳" },
  JPY: { name: "Japanese Yen", symbol: "¥", flag: "🇯🇵" },
  CHF: { name: "Swiss Franc", symbol: "CHF", flag: "🇨🇭" },
  MYR: { name: "Malaysian Ringgit", symbol: "RM", flag: "🇲🇾" },
  THB: { name: "Thai Baht", symbol: "฿", flag: "🇹🇭" },
  ZAR: { name: "South African Rand", symbol: "R", flag: "🇿🇦" },
  RUB: { name: "Russian Ruble", symbol: "₽", flag: "🇷🇺" },
  BRL: { name: "Brazilian Real", symbol: "R$", flag: "🇧🇷" },
  MXN: { name: "Mexican Peso", symbol: "$", flag: "🇲🇽" },
  NZD: { name: "New Zealand Dollar", symbol: "$", flag: "🇳🇿" },
  HKD: { name: "Hong Kong Dollar", symbol: "$", flag: "🇭🇰" },
  KRW: { name: "South Korean Won", symbol: "₩", flag: "🇰🇷" },
  TRY: { name: "Turkish Lira", symbol: "₺", flag: "🇹🇷" },
  EGP: { name: "Egyptian Pound", symbol: "E£", flag: "🇪🇬" },
  IDR: { name: "Indonesian Rupiah", symbol: "Rp", flag: "🇮🇩" },
  VND: { name: "Vietnamese Dong", symbol: "₫", flag: "🇻🇳" },
  PKR: { name: "Pakistani Rupee", symbol: "Rs", flag: "🇵🇰" },
  BDT: { name: "Bangladeshi Taka", symbol: "৳", flag: "🇧🇩" },
  LKR: { name: "Sri Lankan Rupee", symbol: "Rs", flag: "🇱🇰" },
  NPR: { name: "Nepalese Rupee", symbol: "Rs", flag: "🇳🇵" },
  PHP: { name: "Philippine Peso", symbol: "₱", flag: "🇵🇭" },
  ILS: { name: "Israeli Shekel", symbol: "₪", flag: "🇮🇱" },
  JOD: { name: "Jordanian Dinar", symbol: "JD", flag: "🇯🇴" },
  LBP: { name: "Lebanese Pound", symbol: "L£", flag: "🇱🇧" },
  NGN: { name: "Nigerian Naira", symbol: "₦", flag: "🇳🇬" },
  KES: { name: "Kenyan Shilling", symbol: "KSh", flag: "🇰🇪" },
  GHS: { name: "Ghanaian Cedi", symbol: "GH₵", flag: "🇬🇭" },
  MAD: { name: "Moroccan Dirham", symbol: "MAD", flag: "🇲🇦" },
  DZD: { name: "Algerian Dinar", symbol: "DA", flag: "🇩🇿" },
  ARS: { name: "Argentine Peso", symbol: "$", flag: "🇦🇷" },
  CLP: { name: "Chilean Peso", symbol: "$", flag: "🇨🇱" },
  COP: { name: "Colombian Peso", symbol: "$", flag: "🇨🇴" },
  PEN: { name: "Peruvian Sol", symbol: "S/", flag: "🇵🇪" },
  SEK: { name: "Swedish Krona", symbol: "kr", flag: "🇸🇪" },
  NOK: { name: "Norwegian Krone", symbol: "kr", flag: "🇳🇴" },
  DKK: { name: "Danish Krone", symbol: "kr", flag: "🇩🇰" },
  PLN: { name: "Polish Zloty", symbol: "zł", flag: "🇵🇱" },
  HUF: { name: "Hungarian Forint", symbol: "Ft", flag: "🇭🇺" },
  CZK: { name: "Czech Koruna", symbol: "Kč", flag: "🇨🇿" },
  RON: { name: "Romanian Leu", symbol: "lei", flag: "🇷🇴" },
  BGN: { name: "Bulgarian Lev", symbol: "лв", flag: "🇧🇬" },
  TZS: { name: "Tanzanian Shilling", symbol: "TSh", flag: "🇹🇿" },
  UGX: { name: "Ugandan Shilling", symbol: "USh", flag: "🇺🇬" },
  UAH: { name: "Ukrainian Hryvnia", symbol: "₴", flag: "🇺🇦" },
  SOS: { name: "Somali Shilling", symbol: "Sh.So.", flag: "🇸🇴" },
  SLL: { name: "Sierra Leonean Leone", symbol: "Le", flag: "🇸🇱" },
  SRD: { name: "Surinamese Dollar", symbol: "$", flag: "🇸🇷" },
  SSP: { name: "South Sudanese Pound", symbol: "£", flag: "🇸🇸" },
  STN: { name: "São Tomé Dobra", symbol: "Db", flag: "🇸🇹" },
  SYP: { name: "Syrian Pound", symbol: "LS", flag: "🇸🇾" },
  SZL: { name: "Eswatini Lilangeni", symbol: "E", flag: "🇸🇿" },
  TJS: { name: "Tajikistani Somoni", symbol: "SM", flag: "🇹🇯" },
  TMT: { name: "Turkmenistan Manat", symbol: "T", flag: "🇹🇲" },
  TND: { name: "Tunisian Dinar", symbol: "DT", flag: "🇹🇳" },
  TOP: { name: "Tongan Paʻanga", symbol: "T$", flag: "🇹🇴" },
  TTD: { name: "Trinidad Dollar", symbol: "TT$", flag: "🇹🇹" },
  TVD: { name: "Tuvaluan Dollar", symbol: "$", flag: "🇹🇻" },
  TWD: { name: "New Taiwan Dollar", symbol: "NT$", flag: "🇹🇼" },
  AFN: { name: "Afghan Afghani", symbol: "؋", flag: "🇦🇫" },
  ALL: { name: "Albanian Lek", symbol: "L", flag: "🇦🇱" },
  AMD: { name: "Armenian Dram", symbol: "֏", flag: "🇦🇲" },
  ANG: { name: "Neth. Antilles Guilder", symbol: "ƒ", flag: "🇨🇼" },
  AOA: { name: "Angolan Kwanza", symbol: "Kz", flag: "🇦🇴" },
  AWG: { name: "Aruban Florin", symbol: "Afl.", flag: "🇦🇼" },
  AZN: { name: "Azerbaijani Manat", symbol: "₼", flag: "🇦🇿" },
  BAM: { name: "Bosnia Convertible Mark", symbol: "KM", flag: "🇧🇦" },
  BBD: { name: "Barbadian Dollar", symbol: "Bds$", flag: "🇧🇧" },
  BIF: { name: "Burundian Franc", symbol: "FBu", flag: "🇧🇮" },
  BMD: { name: "Bermudian Dollar", symbol: "$", flag: "🇧🇲" },
  BND: { name: "Brunei Dollar", symbol: "B$", flag: "🇧🇳" },
  BOB: { name: "Bolivian Boliviano", symbol: "Bs.", flag: "🇧🇴" },
  BSD: { name: "Bahamian Dollar", symbol: "B$", flag: "🇧🇸" },
  BTN: { name: "Bhutanese Ngultrum", symbol: "Nu.", flag: "🇧🇹" },
  BWP: { name: "Botswana Pula", symbol: "P", flag: "🇧🇼" },
  BYN: { name: "Belarusian Ruble", symbol: "Br", flag: "🇧🇾" },
  BZD: { name: "Belize Dollar", symbol: "BZ$", flag: "🇧🇿" },
  CDF: { name: "Congolese Franc", symbol: "FC", flag: "🇨🇩" },
  CRC: { name: "Costa Rican Colón", symbol: "₡", flag: "🇨🇷" },
  CUP: { name: "Cuban Peso", symbol: "$MN", flag: "🇨🇺" },
  CVE: { name: "Cape Verdean Escudo", symbol: "$", flag: "🇨🇻" },
  DJF: { name: "Djiboutian Franc", symbol: "Fdj", flag: "🇩🇯" },
  DOP: { name: "Dominican Peso", symbol: "RD$", flag: "🇩🇴" },
  ERN: { name: "Eritrean Nakfa", symbol: "Nfk", flag: "🇪🇷" },
  ETB: { name: "Ethiopian Birr", symbol: "Br", flag: "🇪🇹" },
  FJD: { name: "Fijian Dollar", symbol: "FJ$", flag: "🇫🇯" },
  FKP: { name: "Falkland Islands Pound", symbol: "£", flag: "🇫🇰" },
  FOK: { name: "Faroese Króna", symbol: "kr", flag: "🇫🇴" },
  GEL: { name: "Georgian Lari", symbol: "₾", flag: "🇬🇪" },
  GGP: { name: "Guernsey Pound", symbol: "£", flag: "🇬🇬" },
  GIP: { name: "Gibraltar Pound", symbol: "£", flag: "🇬🇮" },
  GMD: { name: "Gambian Dalasi", symbol: "D", flag: "🇬🇲" },
  GNF: { name: "Guinean Franc", symbol: "FG", flag: "🇬🇳" },
  GTQ: { name: "Guatemalan Quetzal", symbol: "Q", flag: "🇬🇹" },
  GYD: { name: "Guyanese Dollar", symbol: "G$", flag: "🇬🇾" },
  HNL: { name: "Honduran Lempira", symbol: "L", flag: "🇭🇳" },
  HRK: { name: "Croatian Kuna", symbol: "kn", flag: "🇭🇷" },
  HTG: { name: "Haitian Gourde", symbol: "G", flag: "🇭🇹" },
  IMP: { name: "Manx Pound", symbol: "£", flag: "🇮🇲" },
  IQD: { name: "Iraqi Dinar", symbol: "ع.د", flag: "🇮🇶" },
  IRR: { name: "Iranian Rial", symbol: "﷼", flag: "🇮🇷" },
  ISK: { name: "Icelandic Króna", symbol: "kr", flag: "🇮🇸" },
  JEP: { name: "Jersey Pound", symbol: "£", flag: "🇯🇪" },
  JMD: { name: "Jamaican Dollar", symbol: "J$", flag: "🇯🇲" },
  KGS: { name: "Kyrgyzstani Som", symbol: "с", flag: "🇰🇬" },
  KHR: { name: "Cambodian Riel", symbol: "៛", flag: "🇰🇭" },
  KMF: { name: "Comorian Franc", symbol: "CF", flag: "🇰🇲" },
  KYD: { name: "Cayman Islands Dollar", symbol: "CI$", flag: "🇰🇾" },
  KZT: { name: "Kazakhstani Tenge", symbol: "₸", flag: "🇰🇿" },
  LAK: { name: "Lao Kip", symbol: "₭", flag: "🇱🇦" },
  LRD: { name: "Liberian Dollar", symbol: "L$", flag: "🇱🇷" },
  LSL: { name: "Lesotho Loti", symbol: "L", flag: "🇱🇸" },
  LYD: { name: "Libyan Dinar", symbol: "LD", flag: "🇱🇾" },
  MDL: { name: "Moldovan Leu", symbol: "L", flag: "🇲🇩" },
  MGA: { name: "Malagasy Ariary", symbol: "Ar", flag: "🇲🇬" },
  MKD: { name: "Macedonian Denar", symbol: "ден", flag: "🇲🇰" },
  MMK: { name: "Myanmar Kyat", symbol: "Ks", flag: "🇲🇲" },
  MNT: { name: "Mongolian Tögrög", symbol: "₮", flag: "🇲🇳" },
  MOP: { name: "Macanese Pataca", symbol: "MOP$", flag: "🇲🇴" },
  MRU: { name: "Mauritanian Ouguiya", symbol: "UM", flag: "🇲🇷" },
  MUR: { name: "Mauritian Rupee", symbol: "₨", flag: "🇲🇺" },
  MVR: { name: "Maldivian Rufiyaa", symbol: "Rf", flag: "🇲🇻" },
  MWK: { name: "Malawian Kwacha", symbol: "MK", flag: "🇲🇼" },
  MZN: { name: "Mozambican Metical", symbol: "MT", flag: "🇲🇿" },
  NAD: { name: "Namibian Dollar", symbol: "N$", flag: "🇳🇦" },
  NIO: { name: "Nicaraguan Córdoba", symbol: "C$", flag: "🇳🇮" },
  PAB: { name: "Panamanian Balboa", symbol: "B/.", flag: "🇵🇦" },
  PGK: { name: "Papua New Guinean Kina", symbol: "K", flag: "🇵🇬" },
  PYG: { name: "Paraguayan Guaraní", symbol: "₲", flag: "🇵🇾" },
  RSD: { name: "Serbian Dinar", symbol: "din.", flag: "🇷🇸" },
  RWF: { name: "Rwandan Franc", symbol: "FRw", flag: "🇷🇼" },
  SBD: { name: "Solomon Islands Dollar", symbol: "SI$", flag: "🇸🇧" },
  SCR: { name: "Seychellois Rupee", symbol: "SR", flag: "🇸🇨" },
  SDG: { name: "Sudanese Pound", symbol: "SDG", flag: "🇸🇩" },
  SHP: { name: "Saint Helena Pound", symbol: "£", flag: "🇸🇭" },
  SLE: { name: "Sierra Leonean Leone", symbol: "Le", flag: "🇸🇱" },
  SVC: { name: "Salvadoran Colón", symbol: "₡", flag: "🇸🇻" },
  SZL: { name: "Eswatini Lilangeni", symbol: "E", flag: "🇸🇿" },
  TND: { name: "Tunisian Dinar", symbol: "DT", flag: "🇹🇳" },
  UYU: { name: "Uruguayan Peso", symbol: "$U", flag: "🇺🇾" },
  UZS: { name: "Uzbekistani Som", symbol: "so'm", flag: "🇺🇿" },
  VES: { name: "Venezuelan Bolívar", symbol: "Bs.S", flag: "🇻🇪" },
  VUV: { name: "Vanuatu Vatu", symbol: "VT", flag: "🇻🇺" },
  WST: { name: "Samoan Tālā", symbol: "WS$", flag: "🇼🇸" },
  XAF: { name: "Central African CFA Franc", symbol: "FCFA", flag: "🌍" },
  XCD: { name: "East Caribbean Dollar", symbol: "EC$", flag: "🇦🇬" },
  XOF: { name: "West African CFA Franc", symbol: "CFA", flag: "🌍" },
  XPF: { name: "CFP Franc", symbol: "₣", flag: "🇵🇫" },
  YER: { name: "Yemeni Rial", symbol: "﷼", flag: "🇾🇪" },
  ZMW: { name: "Zambian Kwacha", symbol: "ZK", flag: "🇿🇲" },
  ZWL: { name: "Zimbabwean Dollar", symbol: "Z$", flag: "🇿🇼" }
};

export const fallbackRates = {
  USD: 1, INR: 83.50, EUR: 0.92, AED: 3.67, GBP: 0.78, SAR: 3.75, QAR: 3.64,
  KWD: 0.31, BHD: 0.38, OMR: 0.38, SGD: 1.35, CAD: 1.36, AUD: 1.52, CNY: 7.24,
  JPY: 154.20, CHF: 0.91, MYR: 4.72, THB: 36.80, ZAR: 18.60, RUB: 92.50,
  BRL: 5.15, MXN: 16.90, NZD: 1.68, HKD: 7.83, KRW: 1380.0, TRY: 32.50,
  EGP: 47.80, IDR: 16200.0, VND: 25400.0, PKR: 278.0, BDT: 110.0, LKR: 300.0,
  NPR: 133.50, PHP: 57.50, ILS: 3.75, JOD: 0.71, LBP: 89500.0, NGN: 1400.0,
  KES: 133.0, GHS: 13.80, MAD: 10.10, DZD: 134.50, ARS: 880.0, CLP: 950.0,
  COP: 3900.0, PEN: 3.72, SEK: 10.85, NOK: 10.95, DKK: 6.95, PLN: 4.02,
  HUF: 365.0, CZK: 23.50, RON: 4.62, BGN: 1.80, TZS: 2580.0, UGX: 3770.0,
  UAH: 39.50, SOS: 570.0, SLL: 22500.0
};
