// Comprehensive 100+ World Languages Database
export const ALL_WORLD_LANGUAGES = [
  { code: 'en', name: 'English', native: 'English', flag: '🇬🇧', region: 'Global / UK / US' },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી', flag: '🇮🇳', region: 'India (Gujarat)' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी', flag: '🇮🇳', region: 'India (National)' },
  { code: 'fr', name: 'French', native: 'Français', flag: '🇫🇷', region: 'France / Canada' },
  { code: 'es', name: 'Spanish', native: 'Español', flag: '🇪🇸', region: 'Spain / Latin America' },
  { code: 'de', name: 'German', native: 'Deutsch', flag: '🇩🇪', region: 'Germany / EU' },
  { code: 'ar', name: 'Arabic', native: 'العربية', flag: '🇦🇪', region: 'UAE / Middle East' },
  { code: 'zh', name: 'Chinese (Simplified)', native: '中文 (简体)', flag: '🇨🇳', region: 'China' },
  { code: 'ja', name: 'Japanese', native: '日本語', flag: '🇯🇵', region: 'Japan' },
  { code: 'ko', name: 'Korean', native: '한국어', flag: '🇰🇷', region: 'South Korea' },
  { code: 'ru', name: 'Russian', native: 'Русский', flag: '🇷🇺', region: 'Russia' },
  { code: 'pt', name: 'Portuguese', native: 'Português', flag: '🇧🇷', region: 'Brazil / Portugal' },
  { code: 'it', name: 'Italian', native: 'Italiano', flag: '🇮🇹', region: 'Italy' },
  { code: 'tr', name: 'Turkish', native: 'Türkçe', flag: '🇹🇷', region: 'Turkey' },
  { code: 'ur', name: 'Urdu', native: 'اردو', flag: '🇵🇰', region: 'Pakistan / India' },
  { code: 'fa', name: 'Persian (Farsi)', native: 'فارسی', flag: '🇮🇷', region: 'Iran' },
  { code: 'sw', name: 'Swahili', native: 'Kiswahili', flag: '🇰🇪', region: 'East Africa' },
  { code: 'th', name: 'Thai', native: 'ไทย', flag: '🇹🇭', region: 'Thailand' },
  { code: 'vi', name: 'Vietnamese', native: 'Tiếng Việt', flag: '🇻🇳', region: 'Vietnam' },
  { code: 'id', name: 'Indonesian', native: 'Bahasa Indonesia', flag: '🇮🇩', region: 'Indonesia' },
  { code: 'ms', name: 'Malay', native: 'Bahasa Melayu', flag: '🇲🇾', region: 'Malaysia' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা', flag: '🇧🇩', region: 'Bangladesh / India' },
  { code: 'pa', name: 'Punjabi', native: 'ਪੰਜਾਬੀ', flag: '🇮🇳', region: 'India (Punjab)' },
  { code: 'mr', name: 'Marathi', native: 'मराठी', flag: '🇮🇳', region: 'India (Maharashtra)' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்', flag: '🇮🇳', region: 'India / Sri Lanka' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు', flag: '🇮🇳', region: 'India (Andhra / Telangana)' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ', flag: '🇮🇳', region: 'India (Karnataka)' },
  { code: 'ml', name: 'Malayalam', native: 'മലയാളം', flag: '🇮🇳', region: 'India (Kerala)' },
  { code: 'nl', name: 'Dutch', native: 'Nederlands', flag: '🇳🇱', region: 'Netherlands' },
  { code: 'pl', name: 'Polish', native: 'Polski', flag: '🇵🇱', region: 'Poland' },
  { code: 'uk', name: 'Ukrainian', native: 'Українська', flag: '🇺🇦', region: 'Ukraine' },
  { code: 'ro', name: 'Romanian', native: 'Română', flag: '🇷🇴', region: 'Romania' },
  { code: 'el', name: 'Greek', native: 'Ελληνικά', flag: '🇬🇷', region: 'Greece' },
  { code: 'hu', name: 'Hungarian', native: 'Magyar', flag: '🇭🇺', region: 'Hungary' },
  { code: 'cs', name: 'Czech', native: 'Čeština', flag: '🇨🇿', region: 'Czech Republic' },
  { code: 'sv', name: 'Swedish', native: 'Svenska', flag: '🇸🇪', region: 'Sweden' },
  { code: 'no', name: 'Norwegian', native: 'Norsk', flag: '🇳🇴', region: 'Norway' },
  { code: 'da', name: 'Danish', native: 'Dansk', flag: '🇩🇰', region: 'Denmark' },
  { code: 'fi', name: 'Finnish', native: 'Suomi', flag: '🇫🇮', region: 'Finland' },
  { code: 'he', name: 'Hebrew', native: 'עברית', flag: '🇮🇱', region: 'Israel' },
  { code: 'fil', name: 'Filipino (Tagalog)', native: 'Filipino', flag: '🇵🇭', region: 'Philippines' }
];
